packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false
allowBuilds:
  node-pty: true
minimumReleaseAgeExclude:
  - '@liustack/modsearch@5.10.3 || 5.10.4'
  - '@nonamelego/dsh-catppuccin@0.5.2'
  - dsh-context@0.54.4
  - dshmarket@1.55.0 || 1.58.0
  - '@ash-qw/dsh-theme-prts@0.1.100'
